/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RedditRouteImport } from './routes/reddit'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as XRouteImport } from './routes/x'
import { Route as TelegramIndexRouteImport } from './routes/telegram.index'
import { Route as TelegramAppRouteImport } from './routes/telegram.app'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronStudioRouteImport } from './routes/api/cron/studio'
import { Route as ApiRedditOauthCallbackRouteImport } from './routes/api/reddit/oauth/callback'
import { Route as ApiRedditOauthStartRouteImport } from './routes/api/reddit/oauth/start'
import { Route as ApiTelegramBotHookRouteImport } from './routes/api/telegram/bot/hook'
import { Route as ApiTelegramOidcCallbackRouteImport } from './routes/api/telegram/oidc/callback'
import { Route as ApiTelegramPhotoRouteImport } from './routes/api/telegram/photo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedditRoute = RedditRouteImport.update({
  id: '/reddit',
  path: '/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramIndexRoute = TelegramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TelegramRoute,
} as any)
const TelegramAppRoute = TelegramAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => TelegramRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronStudioRoute = ApiCronStudioRouteImport.update({
  id: '/api/cron/studio',
  path: '/api/cron/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditOauthCallbackRoute = ApiRedditOauthCallbackRouteImport.update({
  id: '/api/reddit/oauth/callback',
  path: '/api/reddit/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditOauthStartRoute = ApiRedditOauthStartRouteImport.update({
  id: '/api/reddit/oauth/start',
  path: '/api/reddit/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramBotHookRoute = ApiTelegramBotHookRouteImport.update({
  id: '/api/telegram/bot/hook',
  path: '/api/telegram/bot/hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramOidcCallbackRoute = ApiTelegramOidcCallbackRouteImport.update({
  id: '/api/telegram/oidc/callback',
  path: '/api/telegram/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramPhotoRoute = ApiTelegramPhotoRouteImport.update({
  id: '/api/telegram/photo',
  path: '/api/telegram/photo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reddit': typeof RedditRoute
  '/telegram': typeof TelegramRouteWithChildren
  '/x': typeof XRoute
  '/telegram/app': typeof TelegramAppRoute
  '/telegram/': typeof TelegramIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/studio': typeof ApiCronStudioRoute
  '/api/reddit/oauth/callback': typeof ApiRedditOauthCallbackRoute
  '/api/reddit/oauth/start': typeof ApiRedditOauthStartRoute
  '/api/telegram/bot/hook': typeof ApiTelegramBotHookRoute
  '/api/telegram/oidc/callback': typeof ApiTelegramOidcCallbackRoute
  '/api/telegram/photo': typeof ApiTelegramPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reddit': typeof RedditRoute
  '/x': typeof XRoute
  '/telegram/app': typeof TelegramAppRoute
  '/telegram': typeof TelegramIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/studio': typeof ApiCronStudioRoute
  '/api/reddit/oauth/callback': typeof ApiRedditOauthCallbackRoute
  '/api/reddit/oauth/start': typeof ApiRedditOauthStartRoute
  '/api/telegram/bot/hook': typeof ApiTelegramBotHookRoute
  '/api/telegram/oidc/callback': typeof ApiTelegramOidcCallbackRoute
  '/api/telegram/photo': typeof ApiTelegramPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reddit': typeof RedditRoute
  '/telegram': typeof TelegramRouteWithChildren
  '/x': typeof XRoute
  '/telegram/app': typeof TelegramAppRoute
  '/telegram/': typeof TelegramIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/studio': typeof ApiCronStudioRoute
  '/api/reddit/oauth/callback': typeof ApiRedditOauthCallbackRoute
  '/api/reddit/oauth/start': typeof ApiRedditOauthStartRoute
  '/api/telegram/bot/hook': typeof ApiTelegramBotHookRoute
  '/api/telegram/oidc/callback': typeof ApiTelegramOidcCallbackRoute
  '/api/telegram/photo': typeof ApiTelegramPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reddit'
    | '/telegram'
    | '/x'
    | '/telegram/app'
    | '/telegram/'
    | '/api/auth/$'
    | '/api/cron/studio'
    | '/api/reddit/oauth/callback'
    | '/api/reddit/oauth/start'
    | '/api/telegram/bot/hook'
    | '/api/telegram/oidc/callback'
    | '/api/telegram/photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reddit'
    | '/x'
    | '/telegram/app'
    | '/telegram'
    | '/api/auth/$'
    | '/api/cron/studio'
    | '/api/reddit/oauth/callback'
    | '/api/reddit/oauth/start'
    | '/api/telegram/bot/hook'
    | '/api/telegram/oidc/callback'
    | '/api/telegram/photo'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reddit'
    | '/telegram'
    | '/x'
    | '/telegram/app'
    | '/telegram/'
    | '/api/auth/$'
    | '/api/cron/studio'
    | '/api/reddit/oauth/callback'
    | '/api/reddit/oauth/start'
    | '/api/telegram/bot/hook'
    | '/api/telegram/oidc/callback'
    | '/api/telegram/photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RedditRoute: typeof RedditRoute
  TelegramRoute: typeof TelegramRouteWithChildren
  XRoute: typeof XRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronStudioRoute: typeof ApiCronStudioRoute
  ApiRedditOauthCallbackRoute: typeof ApiRedditOauthCallbackRoute
  ApiRedditOauthStartRoute: typeof ApiRedditOauthStartRoute
  ApiTelegramBotHookRoute: typeof ApiTelegramBotHookRoute
  ApiTelegramOidcCallbackRoute: typeof ApiTelegramOidcCallbackRoute
  ApiTelegramPhotoRoute: typeof ApiTelegramPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reddit': {
      id: '/reddit'
      path: '/reddit'
      fullPath: '/reddit'
      preLoaderRoute: typeof RedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/': {
      id: '/telegram/'
      path: '/'
      fullPath: '/telegram/'
      preLoaderRoute: typeof TelegramIndexRouteImport
      parentRoute: typeof TelegramRoute
    }
    '/telegram/app': {
      id: '/telegram/app'
      path: '/app'
      fullPath: '/telegram/app'
      preLoaderRoute: typeof TelegramAppRouteImport
      parentRoute: typeof TelegramRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/studio': {
      id: '/api/cron/studio'
      path: '/api/cron/studio'
      fullPath: '/api/cron/studio'
      preLoaderRoute: typeof ApiCronStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/oauth/callback': {
      id: '/api/reddit/oauth/callback'
      path: '/api/reddit/oauth/callback'
      fullPath: '/api/reddit/oauth/callback'
      preLoaderRoute: typeof ApiRedditOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/oauth/start': {
      id: '/api/reddit/oauth/start'
      path: '/api/reddit/oauth/start'
      fullPath: '/api/reddit/oauth/start'
      preLoaderRoute: typeof ApiRedditOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/bot/hook': {
      id: '/api/telegram/bot/hook'
      path: '/api/telegram/bot/hook'
      fullPath: '/api/telegram/bot/hook'
      preLoaderRoute: typeof ApiTelegramBotHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/oidc/callback': {
      id: '/api/telegram/oidc/callback'
      path: '/api/telegram/oidc/callback'
      fullPath: '/api/telegram/oidc/callback'
      preLoaderRoute: typeof ApiTelegramOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/photo': {
      id: '/api/telegram/photo'
      path: '/api/telegram/photo'
      fullPath: '/api/telegram/photo'
      preLoaderRoute: typeof ApiTelegramPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TelegramRouteChildren {
  TelegramAppRoute: typeof TelegramAppRoute
  TelegramIndexRoute: typeof TelegramIndexRoute
}

const TelegramRouteChildren: TelegramRouteChildren = {
  TelegramAppRoute: TelegramAppRoute,
  TelegramIndexRoute: TelegramIndexRoute,
}

const TelegramRouteWithChildren = TelegramRoute._addFileChildren(
  TelegramRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RedditRoute: RedditRoute,
  TelegramRoute: TelegramRouteWithChildren,
  XRoute: XRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronStudioRoute: ApiCronStudioRoute,
  ApiRedditOauthCallbackRoute: ApiRedditOauthCallbackRoute,
  ApiRedditOauthStartRoute: ApiRedditOauthStartRoute,
  ApiTelegramBotHookRoute: ApiTelegramBotHookRoute,
  ApiTelegramOidcCallbackRoute: ApiTelegramOidcCallbackRoute,
  ApiTelegramPhotoRoute: ApiTelegramPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
